version: '3'

services:
  db:
    build: ./srcs/requirements/mariadb
    image: my_maria:latest
    container_name: db
    env_file: .env
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - all_connect
  wordpress:
    depends_on:
      - db
    build: ./srcs/requirements/wordpress
    image: my_wordpress:latest
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - all_connect
  nginx:
    depends_on:
      - wordpress
    build: ./srcs/requirements/nginx
    image: my_nginx:latest
    container_name: website
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - all_connect
  static_website:
    depends_on:
      - nginx
    build: ./srcs/bonus/static_website
    image: my_static:latest
    container_name: static_website
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - all_connect

volumes:
  wordpress:
  dbdata:

networks:
  all_connect:
    driver: bridge
