version: '3'

services:
  db:
    build: ./srcs/requirements/mariadb
    image: my_maria:latest
    container_name: db
    env_file: .env
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_USER=wordpress_user
      - WORDPRESS_PASS=pass
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - all_connect
  wordpress:
    depends_on:
      - db
      - redis
    build: ./srcs/requirements/wordpress
    image: my_wordpress:latest
    container_name: wordpress
    env_file: .env
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_USER=wordpress_user
      - WORDPRESS_PASS=pass
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - all_connect
  nginx:
    depends_on:
      - wordpress
    build: ./srcs/requirements/nginx
    image: my_nginx:latest
    container_name: website
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - all_connect
  static_website:
    depends_on:
      - nginx
    build: ./srcs/bonus/static_website
    image: my_static:latest
    container_name: static_website
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - all_connect
  redis:
    build: ./srcs/bonus/redis
    image: my_redis:latest
    container_name: redis
    volumes:
      - redis:/data
    networks:
      - all_connect
  adminer:
    build: ./srcs/bonus/adminer
    image: my_adminer:latest
    container_name: adminer
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - all_connect
  redis_commander:
    build: ./srcs/bonus/redis_commander
    image: my_redis_commander:latest
    container_name: redis_commander
    ports:
      - 8081:8081
    networks:
      - all_connect

volumes:
  wordpress:
  dbdata:
  redis:

networks:
  all_connect:
    driver: bridge
