CREATE DATABASE IF NOT EXISTS ${WORDPRESS_DB_NAME};
CREATE USER '${WORDPRESS_USER}'@'%' IDENTIFIED BY '${WORDPRESS_PASS}';
GRANT ALL ON ${WORDPRESS_DB_NAME}.* TO '${WORDPRESS_USER}'@'%';
FLUSH PRIVILEGES;
