CREATE DATABASE IF NOT EXISTS {WORDPRESS_DB_NAME};

CREATE USER '{WORDPRESS_USER}'@'%' IDENTIFIED BY '{WORDPRESS_PASS}';

CREATE USER '{WORDPRESS_USER2}'@'%' IDENTIFIED BY '{WORDPRESS_PASS2}';

GRANT ALL ON {WORDPRESS_DB_NAME}.* TO '{WORDPRESS_USER}'@'%' WITH GRANT OPTION;
ALTER USER 'root'@'localhost' IDENTIFIED BY '{WORDPRESS_PASS}';
FLUSH PRIVILEGES;

